apiVersion: v1
kind: ImageStream
metadata:
  labels:
    application: git-triggers-build
name: git-triggers-build
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: git-triggers-build
  name: git-triggers-build
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: git-triggers-build
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    application: git-triggers-build
  name: git-triggers-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: git-triggers-build:latest
  source:
    git:
      ref: master
      uri: https://github.com/cassiussa/git-triggers-build_openshift.git
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: jboss-eap64-openshift:latest
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: somethinghere
    type: GitHub
  - generic:
      secret: somethingthere
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: git-triggers-build
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: git-triggers-build
            name: git-triggers-build
        spec:
          containers:
          - image: git-triggers-build:latest
            imagePullPolicy: Always
            name: git-triggers-build
            ports:
            - containerPort: 8000
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /repositories
              name: git-triggers-build-repositories
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: git-triggers-build-repositories
            secret:
              defaultMode: 420
              secretName: git-triggers-build-secret
  schedule: '*/5 * * * *'
  suspend: false
